### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by oneilsw** [HTFML/chinese-poker#12]
-once the application loads, an initial splashScreen will render. After a certain amount of time(3 seconds maybe), the homeScreen will render.
-a nice graphic would be nice. For now, it can literally say "Splash Screen"

**Comment by speckworks** [comment]
Did you make a folder for graphics inspiration?

**Comment by oneilsw** [comment]
in the app.json file, change the "image" to something relevant

 "splash": {
      "image": "./assets/splash.png"
  }
