### ISSUE TITLE
Rules page

### ISSUE THREAD

**Issue by oneilsw** [HTFML/chinese-poker#35]
- Remove "Home" button at the bottom of the page.
- Fix "Warning: Failed prop type: Invalid props.style key `backgroundImage` supplied to `Text`."

**Comment by speckworks** [comment]
@oneilsw Is that error from an iOS emulator?  The web browser rulespage branch doesn't give that error. I don't have XCode installed for ios emulator.

**Comment by oneilsw** [comment]
@speckworks We have to see if the application will work on mobile first and foremost. I am getting that error from the ios simulator. When you run it on the android simulator, does everything load correctly?
